<?php
/**
 * Created by PhpStorm.
 * User: suwen
 * Date: 2017/10/14
 * Time: 15:26
 */

namespace backend\controllers;

use yii\web\Controller;

class BaseController extends Controller{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}