<?php
/**
 * Created by PhpStorm.
 * User: suwen
 * Date: 2017/10/14
 * Time: 15:26
 */

namespace backend\controllers;

use yii\web\Controller;

class BaseController extends Controller{
    public $currentPage;//当前页面
    public function init()
    {
        if (\Yii::$app->session['admin']['isLogin'] != 1) {
            return $this->redirect(['/manager/public/login']);
        }
        parent::init(); // TODO: Change the autogenerated stub
    }
}