<?php
/**
 * Created by PhpStorm.
 * User: suwen
 * Date: 2017/10/14
 * Time: 15:55
 */

namespace backend\modules\manager;

/** 管理员模块
 * Class Manager
 * @package backend\modules\manager
 */
class Manager extends \yii\base\Module{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}