<?php
/**
 * Created by PhpStorm.
 * User: suwen
 * Date: 2017/10/14
 * Time: 15:57
 */

namespace backend\modules\system;

/** 系统设置模块
 * Class System
 * @package backend\modules\system
 */
class System extends \yii\base\Module{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}