<?php
/** 控制器基类
 * Created by PhpStorm.
 * User: suwen
 * Date: 2017/10/5
 * Time: 19:15
 */

namespace pc\controllers;

use yii\web\Controller;
use pc\logics\BaseBlocks;

/** pc端控制器基类
 * Class BaseController
 * @package pc\controllers
 */
class BaseController extends Controller
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}