<?php
/** 控制器基类
 * Created by PhpStorm.
 * User: suwen
 * Date: 2017/10/5
 * Time: 19:15
 */

namespace pc\controllers;

use yii\web\Controller;
use pc\logics\BaseBlocks;

/** pc端控制器基类
 * Class BaseController
 * @package pc\controllers
 */
class BaseController extends Controller
{
    function beforeAction($action)
    {
        return parent::beforeAction($action);
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 判断是否登录
     */
    public function checkLogin(){

    }

    /**
     * 当前时间
     */
    public function getDateTime(){
        return date("Y-m-d H:i:s",time());
    }

}