<?php
/** 控制器基类
 * Created by PhpStorm.
 * User: suwen
 * Date: 2017/10/5
 * Time: 19:15
 */

namespace wap\controllers;

use yii\web\Controller;
use wap\logics\BaseBlocks;

/** pc端控制器基类
 * Class BaseController
 * @package pc\controllers
 */
class BaseController extends Controller
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 判断是否登录
     * @author ldz
     * @time 2017-12-17 00:04:51
     */
    public function bLogin()
    {
        if (array_key_exists('lifetime', $_SESSION)) {
            if ($_SESSION['lifetime'] && $_SESSION['lifetime'] > time()) {
                return true;
            } else {
                return false;
            }
        }else{
            return false;
        }
    }


}