<?php
/**
 * Created by PhpStorm.
 * User: suwen
 * Date: 2017/10/14
 * Time: 15:52
 */

namespace backend\modules\marketing;

/** 营销模块
 * Class Marketing
 * @package backend\modules\marketing
 */
class Marketing extends \yii\base\Module{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}