<?php
/**
 * Created by PhpStorm.
 * User: suwen
 * Date: 2017/10/14
 * Time: 15:55
 */

namespace backend\modules\member;

/** 会员模块
 * Class Member
 * @package backend\modules\member
 */
class Member extends \yii\base\Module{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}